### ISSUE TITLE
deepin 20.8安装1.3.10 deb后打开界面一片空白

### ISSUE THREAD

**Issue by photongh** [Fclash/Fclash#34]
求助，如题，界面一片空白，也不能退出，界面如下：

![截图_选择区域_20230302150827](https://user-images.githubusercontent.com/6993662/222356126-864c40f6-915a-40a4-9ffd-32313120ac2d.png)

使用命令行执行 `/opt/apps/cn.kingtous.fclash/files/fclash`也是一片空白，命令行显示以下内容：

```
(fclash:61791): dbind-WARNING **: 15:11:39.076: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(fclash:61791): GLib-CRITICAL **: 15:11:39.157: the GVariant format string 'v' has a type of 'v' but the given value has a type of 's'

(fclash:61791): GLib-CRITICAL **: 15:11:39.157: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(fclash:61791): GLib-CRITICAL **: 15:11:39.157: g_variant_dict_insert_value: assertion 'value != NULL' failed

** (fclash:61791): CRITICAL **: 15:11:39.158: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

(fclash:61791): GLib-CRITICAL **: 15:11:39.158: the GVariant format string 'v' has a type of 'v' but the given value has a type of 'b'

(fclash:61791): GLib-CRITICAL **: 15:11:39.158: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(fclash:61791): GLib-CRITICAL **: 15:11:39.158: g_variant_dict_insert_value: assertion 'value != NULL' failed

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: the GVariant format string 'v' has a type of 'v' but the given value has a type of 's'

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: g_variant_dict_insert_value: assertion 'value != NULL' failed

** (fclash:61791): CRITICAL **: 15:11:39.159: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: the GVariant format string 'v' has a type of 'v' but the given value has a type of 'd'

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed

(fclash:61791): GLib-CRITICAL **: 15:11:39.159: g_variant_dict_insert_value: assertion 'value != NULL' failed
Dart Api DL is initialized
flutter: fclash work directory: /home/xxx/.local/share/cn.kingtous.fclash/clash
GO: set home dir to /home/xxx/.local/share/cn.kingtous.fclash/clash
INFO[0000] Can't find config, create a initial config file 
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:22346 
INFO[0000] RESTful API listening at: 127.0.0.1:22345    
INFO[0000] HTTP proxy listening at: 127.0.0.1:12346     
INFO[0000] SOCKS proxy listening at: 127.0.0.1:12347    
flutter: type 'Null' is not a subtype of type 'bool' in type cast
flutter: #0      SpUtil.getData (package:kommon/tool/sp_util.dart:82)
flutter: #1      ThemeController.isDark (package:fclash/screen/controller/theme_controller.dart:7)
flutter: #2      ThemeController.getThemeMode (package:fclash/screen/controller/theme_controller.dart:10)
flutter: #3      MyApp.build (package:fclash/main.dart:110)
flutter: #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
flutter: #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176)
flutter: #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145)
flutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092)
flutter: #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682)
flutter: #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091)
flutter: #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926)
flutter: #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906)
flutter: #18     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420)
flutter: #21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
flutter: (elided 2 frames from class _Timer)

(fclash:61791): libayatana-appindicator-WARNING **: 15:11:39.197: Unable to connect to the Notification Watcher: GDBus.Error:com.deepin.DBus.Error.Unnamed: notifier item has been registered

(fclash:61791): libayatana-appindicator-WARNING **: 15:11:39.213: Unable to connect to the Notification Watcher: GDBus.Error:com.deepin.DBus.Error.Unnamed: notifier item has been registered
```

**Comment by Kingtous** [comment]
感谢反馈，我看看

**Comment by photongh** [comment]
> 感谢反馈，我看看

好的谢谢，有什么其他log需要提供的可以告诉我，我去操作

**Comment by Kingtous** [comment]
你可以试图修复一下

**Comment by photongh** [comment]
> 你可以试图修复一下

@Kingtous 怎么修复呢

**Comment by jalenzz** [comment]
ubuntu 20.04 也出现一样的状况

**Comment by Kingtous** [comment]
这两天有空我看看，要是大家有空可以pr一下，就是一个null问题

**Comment by Kingtous** [comment]
请更新1.3.11，或者等待星火商店审核通过

**Comment by photongh** [comment]
> 请更新1.3.11，或者等待星火商店审核通过

可以了，感谢
